linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - testdata

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
